### ISSUE TITLE
Phase 3 first quarter LinkML task list

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/data-model-harmonization#20]
## Task list
- [ ] 1. Implement Inheritance
- [ ] 2. Implement Codeable Concept Binding
- [ ] 3. Document profiling approach on the documentation site
- [ ] 4. Implement profile definition (i.e. Observation classes)
- [ ] 5. Define / implement multiple types per field
- [ ] 6. Synonyms for entity/attribute
- [ ] 7. Automated generation of overview diagram
- [ ] 8. Indication and documentation of which classes are complex data types and which are top-level entities that can be instantiated

## More info
Task | Main repo
-|-
1 | [sheet2linkml](https://github.com/cancerDHC/sheet2linkml)
2 | ?
3 | ?
4 | ?
5 | ?
6 | ?
7 | ?
8 | ?

**Comment by joeflack4** [comment]
Is inheritance already implemented, or is there something missing?

From the docs:
- https://github.com/linkml/linkml
- https://linkml.io/linkml-model/docs/is_a

<img width="844" alt="Screen Shot 2021-08-02 at 2 53 30 PM" src="https://user-images.githubusercontent.com/13045020/127909836-dba5ca2b-6746-4f73-8f64-d9d9fdc8b207.png">

**Comment by gaurav** [comment]
Yeah, I'm waiting for DMH to specify this fully (Shahim is working on a really good document that does this), but I think *most* of what they need for inheritance is already implemented in LinkML. Except for profiles, which we could probably implement in the Google Sheets to LinkML program (given enough time).

**Comment by joeflack4** [comment]
@bfurner Hey Brian. I'm starting to work a lot more on LinkML right now. I'm wondering, (a) are all of these tasks things that need to be done within the LinkML codebase, (b) or are these just for our utilization / presentation of LinkML? Or (c) both?

If (a) or (c), can you list out which of these individual tasks needs to be handled w/in the LinkML codebase?

I've made a reference to this in the LinkML issues: https://github.com/linkml/linkml/issues/276

**Comment by bfurner** [comment]
@joeflack4 thanks.  it would probably be worth finding a time to chat on this.  i'm not sure i fully understand what you mean by "w/in the LinkML codebase".  i assume this is to distinguish from something like sheet2linkml which is a separate codebase??

in terms of item 1 (inheritance), this is something that LinkML supports but that sheet2linkml doesn't handle AFAIK.  for example, we define an entity named Entity that really should be the base class from which any entity in the model that requires an id inherits from, but we're not handling this now in sheet2linkml.  we need a clear understanding of how to encode inheritance in the CDM sheet so that this can be picked up in sheet2linkml.  perhaps this is as simple as indicating the type from which an entity inherits in the 'Type' column of the CDM for the row w/o an attribute (i.e. row 2).  that seems a little fragile so it would be good to hear from you or @gaurav on how this might be most easily incorporated into sheet2linkml.

item 2 is essentially a path-based binding.  in other words being able to say that one attribute whose range is CodeableConcept (e.g. CancerStageObervation.observation_type) should have its coding.code bound to a particular codeset whereas another CodeableConcept (e.g. CancerStageObervation.value_codeable_concept) should have its coding.code bound to a different codeset.

**Comment by bfurner** [comment]
probably worth spending an upcoming cross workstream on this topic

**Comment by joeflack4** [comment]
@bfurner Sorry for my delay in response. Good idea; I'll add that to the agenda for next time.

I was 2 months fresher than i am now when I wrote what I wrote, so I knew even less about what was going on. But yeah, I'm not sure just looking at it where each of the work needs to be done and who needs to do it, so it would be good to discuss.

I edited the original post with a table where we can add more information about which repo the task needs to be done in. We could add other stuff to this table if needed.
